apiVersion: v1
kind: Service
metadata:
  name: pigallery2
  namespace: pigallery2
spec:
  selector:
    app: pigallery2
  ports:
    - name: pigallery2-web
      protocol: TCP
      port: 80
      targetPort: 80
