apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: homeassistant-data
          persistentVolumeClaim:
            claimName: homeassistant-pvc-data
      containers:
        - image: docker.io/homeassistant/home-assistant:stable
          name: homeassistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: homeassistant-data
          resources: {}
