apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  rules:
    - host: ha.imagilan
      http:
        paths:
          - backend:
              service:
                name: homeassistant
                port:
                  name: ha-web
            pathType: Prefix
            path: "/"
