apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv-filesystem-data
  namespace: homeassistant
spec:
  capacity:
    storage: 30Gi
  hostPath:
    path: /srv/k8s/pv/homeassistant
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
