apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
