apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plexserver
  namespace: plexserver
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
        - plex.imagilan.imaginator.com
      secretName: plex.imagilan.imaginator.com-tls
  rules:
    - host: plex.imagilan.imaginator.com
      http:
        paths:
          - backend:
              service:
                name: plexserver
                port:
                  name: pms-web
            pathType: Prefix
            path: "/"
