apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-filesystem-config       # < name of the persisant volume ("pv") in kubenetes
  namespace: plexserver                       # < namespace where place the pv
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/test/config
    type: ''
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-filesystem-data
  namespace: plexserver
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/test/data
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-filesystem-film
  namespace: plexserver
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/video/Film
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-filesystem-tv
  namespace: plexserver
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/video/TV
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-filesystem-audiobooks
  namespace: plexserver
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/audio/audiobooks
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-filesystem-photos
  namespace: plexserver
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/photos
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexserver-pv-filesystem-music
  namespace: plexserver
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/audio/music/Music
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
